### PR TITLE
Feature paging nav

### PR DESCRIPTION
**Pull request by ebeutler**

### CODE REVIEW

**Comment by fpichler** [comment]
add missing unit tests and fixed implementation. Can you please review.

**Comment by msladek** [comment]
Two questions to consider from my part:
1. offset isn't considered at all if nrOfItemsPerPage isn't set. Is this intentional? Can't/shouldn't the client be able to use offset on it's own?
2. Wouldn't it be less error-prone to treat nrOfItemsPerPage =  0 like -1? I can't imagine a sensible use case where one would want to return 0 items.

**Comment by fpichler** [comment]
- added support for offset without paging
- handling of "nrOfItemsPerPage = 0 like -1" has been there already
Please code review and merge if possible?

**Comment by msladek** [comment]
yes you are right, its already in there. Looks good now to me.

**Pull request merged**
